### ISSUE TITLE
v1.1.0 Error: Implicit declaration of function 'OBDebug' is invalid in C99

### ISSUE THREAD

**Issue by remypanicker** [outboundio/ios-sdk#9]
I've installed [Outbound v1.1.0](https://github.com/outboundio/ios-sdk/commit/5ef1b96daaa4bbeac356fa0982bce4e69e90995f) and receive the following error which prevents me from compiling my app with Outbound integrated:

**OBNetwork.m:98:5:** Implicit declaration of function 'OBDebug' is invalid in C99

**Comment by ryan-scott-dev** [comment]
Hi @remypanicker 
Thats an unusual one, `OBDebug` is defined in `Outbound-Prefix.pch` which if the SDK is used via CocoaPods should be added as the prefix header for every file in the target.

Can I ask how you are including the SDK? 
Also if the `Prefix Header` for your Outbound target includes `Outbound-prefix.pch`?

**Comment by remypanicker** [comment]
Ah, I didn't notice there was a precompiled header. 

I'm integrating the Outbound SDK with a Swift project (no `.pch`) using `git submodules` as opposed to `CocoaPods`. 

Including the prefix header fixed the issue.
